### ISSUE TITLE
Error when running any command after most recent install

### ISSUE THREAD

**Issue by AlexanderFuentes** [McGillX/edx_data_research#39]
Traceback (most recent call last):
  File "/usr/local/bin/moocx", line 9, in <module>
    load_entry_point('moocx==0.1.0', 'console_scripts', 'moocx')()
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 356, in load_entry_point

  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 2476, in load_entry_point
    self._pkg_info = Parser().parsestr(self.get_metadata(self.PKG_INFO))
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 2190, in load
    self._provider = metadata or empty_provider
  File "/usr/local/lib/python2.7/dist-packages/moocx-0.1.0-py2.7.egg/edx_data_research/cli/cli.py", line 7, in <module>
    from edx_data_research.cli import commands
  File "/usr/local/lib/python2.7/dist-packages/moocx-0.1.0-py2.7.egg/edx_data_research/cli/commands.py", line 6, in <module>
    from edx_data_research import reporting
  File "/usr/local/lib/python2.7/dist-packages/moocx-0.1.0-py2.7.egg/edx_data_research/reporting/__init__.py", line 1, in <module>
    from report_basic import Basic
  File "/usr/local/lib/python2.7/dist-packages/moocx-0.1.0-py2.7.egg/edx_data_research/reporting/report_basic.py", line 7, in <module>
    from edx_data_research.reporting.lib import geoip
ImportError: No module named lib

**Comment by ueg1990** [comment]
should be working now
